version: '3'

services:
  db:
    image: postgres:14.5
    restart: on-failure
    expose:
      - 5432
    volumes:
      - pg:/var/lib/postgresql
    env_file:
      - ./.env
    networks:
      - container_network
  app:
    build: ./app
    restart: always
    ports:
      - 1337:3000
    volumes:
      - go_modules:/go/pkg/mod
    env_file:
      - ./.env
    networks:
      - container_network
    depends_on:
      - db
    command: ./app_exec

volumes:
  pg:
  go_modules:

networks:
  container_network:
